name: release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
